/*!
 * pldr.js 1.1.0 by pldrjs
 * Copyright 2015-2016 HelloWorld017 <deu07115@gmail.com>,onebone <jyc00410@gmail.com>
 * Licensed under the GPL-3.0 license
 */
"use strict";function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function")}function _possibleConstructorReturn(a,b){if(!a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!b||"object"!=typeof b&&"function"!=typeof b?a:b}function _inherits(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}}),b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,b):a.__proto__=b)}var $=new JavaImporter(java.lang,java.lang.reflect,java.io,java.util,java.util.stream,java.nio.file,Packages.cn.nukkit.plugin,Packages.cn.nukkit.event,Packages.cn.nukkit.item,Packages.cn.nukkit.math,Packages.cn.nukkit.block,Packages.cn.nukkit.level,Packages.cn.nukkit.level.particle),EventEmitter=require("events"),PldrJS={},PldrEventEmitter=function(a){function b(){return _classCallCheck(this,b),_possibleConstructorReturn(this,Object.getPrototypeOf(b).apply(this,arguments))}return _inherits(b,a),b}(EventEmitter),PldrEvent=new PldrEventEmitter,propertySetter=function(a){return function(b,c){return void 0!==c?void(b[a]=c):b[a]}},eventHandlerSetter=function(a){return function(b){PldrJS.Script.Event.on(a,b)}},eventHookSetter=function(a){return function(){for(var b,c=arguments.length,d=Array(c),e=0;e<c;e++)d[e]=arguments[e];return(b=PldrJS.Script.Event).emit.apply(b,[a].concat(d))}};PldrJS.disabled=eventHandlerSetter("disabled"),PldrJS.modTick=PldrJS.tick=eventHandlerSetter("tick"),PldrJS.command=function(a,b){PldrJS.Script.Event.on("command:"+a,b)},PldrJS.disabledHook=eventHookSetter("disabled"),PldrJS.tickHook=eventHookSetter("tick"),PldrJS.commandHook=function(){for(var a=arguments.length,b=Array(a),c=0;c<a;c++)b[c]=arguments[c];return PldrJS.Script.Event.listeners("command:"+b[0]).some(function(a){return a.apply(void 0,b)})},PldrJS.getPlugin=function(){return PldrJSPlugin},PldrJS.getServer=function(){return PldrJS.getPlugin().getServer()},PldrJS.getPluginManager=function(){return PldrJS.getServer().getPluginManager()},PldrJS.print=function(a){PldrJS.getPlugin().getLogger().info(a)},PldrJS.console=PldrJS.getPlugin().getLogger();var field=PldrJS.getPluginManager().getClass().getDeclaredField("commandMap");if(field.setAccessible(!0),PldrJS.commandList=field.get(PldrJS.getPluginManager()),PldrJS.registerCommand=function(a,b,c){var d=Java.extend(Java.type("cn.nukkit.command.Command"),{execute:function(b,c,d){return PldrJS.commandHook(a,b,c,d)}});PldrJS.commandList.register("PldrJS",new d(a,b,c))},
// ModPE-like Environment
// Please refer to https://github.com/Connor4898/ModPE-Docs/wiki
// and https://duggum.github.io/modpe-api/
//======Block=======
PldrJS.Block={},
//======Entity======
PldrJS.Entity={},PldrJS.Entity.setX=PldrJS.Entity.getX=PldrJS.Entity.x=function(a,b){return void 0===b?a.x:void a.teleport(new $.Vector3(b,a.y,a.z))},PldrJS.Entity.setY=PldrJS.Entity.getY=PldrJS.Entity.y=function(a,b){return void 0===b?a.y:void a.teleport(new $.Vector3(a.x,b,a.z))},PldrJS.Entity.setZ=PldrJS.Entity.getZ=PldrJS.Entity.z=function(a,b){return void 0===b?a.z:void a.teleport(new $.Vector3(a.x,a.y,b))},PldrJS.Entity.teleport=function(a,b,c,d){a.teleport(new $.Vector3(b,c,d))},PldrJS.Entity.setVelX=PldrJS.Entity.getVelX=PldrJS.Entity.velX=propertySetter("motionX"),PldrJS.Entity.setVelY=PldrJS.Entity.getVelY=PldrJS.Entity.velY=propertySetter("motionY"),PldrJS.Entity.setVelZ=PldrJS.Entity.getVelZ=PldrJS.Entity.velZ=propertySetter("motionZ"),PldrJS.Entity.setPitch=PldrJS.Entity.getPitch=PldrJS.Entity.pitch=propertySetter("pitch"),PldrJS.Entity.setYaw=PldrJS.Entity.getYaw=PldrJS.Entity.yaw=propertySetter("yaw"),PldrJS.Entity.getLevel=PldrJS.Entity.setLevel=PldrJS.Entity.level=function(a,b){return void 0!==b?void a.setLevel(b):a.getLevel()},
//======Event=======
PldrJS.Event={},PldrJS.Event.emit=function(a){PldrJS.getPluginManager().callEvent(a)},PldrJS.Event.getEvent=function(a){return Java.type(PldrJS.Event.getKnownEvents().get(a).getCanonicalName())},PldrJS.Event.getKnownEvents=function(){return PldrJSEvents},PldrJS.Event.on=function(a,b,c){var d=Java.type("cn.nukkit.plugin.EventExecutor"),e=Java.extend(d,{execute:function(a,c){
//handle on executor, not on listener because nashorn does not support creating new method.
b.apply({preventDefault:function(){c.setCancelled()}},[c])}}),f=Java.type("cn.nukkit.event.Listener"),g=Java.extend(f,{}),h=c?$.EventPriority[c.toUpperCase()]:$.EventPriority.NORMAL,i=PldrJS.Event.getKnownEvents().containsKey(a)?PldrJS.Event.getKnownEvents().get(a):$.Class.forName(a),j=PldrJS.getPluginManager();j.registerEvent(i,new g,h,new e,PldrJS.getPlugin())},
//=======Item=======
PldrJS.Item={},
//======Level=======
PldrJS.Level={},PldrJS.Level.addParticle=function(a,b,c,d,e,f){var g=new $.Vector3(c,d,e),h=void 0!==f?new $.GenericParticle(g,b,f):new $.GenericParticle(g,b);a.addParticle(h)},PldrJS.Level.addColoredParticle=function(a,b,c,d,e,f,g,h){return PldrJS.Level.addParticle(a,PldrJS.ParticleType.dust,b,c,d,(255&e)<<24|(255&f)<<16|(255&g)<<8|255&h)},PldrJS.Level.setTile=function(a,b,c,d,e,f){a.setBlock(new $.Vector3(b,c,d),new $.Block(e,f))},PldrJS.Level.getTile=function(a,b,c,d){return a.getBlock(new $.Vector3(b,c,d))},PldrJS.Level.explode=function(a,b,c,d,e,f){var g=new $.Position(b,c,d,a),h=new $.Explosion(g,e,null);f&&h.explodeA(),h.explodeB()},PldrJS.Level.getLevel=function(a){return PldrJS.getServer().getLevelByName(a)},PldrJS.Level.getName=function(a){return a.getFolderName()},
//======ParticleType======
PldrJS.ParticleType={},$.Arrays.asList($.Particle["class"].getDeclaredFields()).forEach(function(a){$.Modifier.isStatic(a.getModifiers())&&a.getName().startsWith("TYPE_")&&(PldrJS.ParticleType[a.getName().replaceFirst("TYPE_","").toLowerCase()]=a.get(null))}),
//======Player======
PldrJS.Player={},PldrJS.Player.getCarriedItem=function(a){return a.getInventory().getItemInHand()},PldrJS.Player.x=PldrJS.Player.setX=PldrJS.Player.getX=PldrJS.Entity.x,PldrJS.Player.y=PldrJS.Player.setY=PldrJS.Player.getY=PldrJS.Entity.y,PldrJS.Player.z=PldrJS.Player.setZ=PldrJS.Player.getZ=PldrJS.Entity.z,PldrJS.Player.setVelX=PldrJS.Player.getVelX=PldrJS.Player.velX=PldrJS.Entity.velX,PldrJS.Player.setVelY=PldrJS.Player.getVelY=PldrJS.Player.velY=PldrJS.Entity.velY,PldrJS.Player.setVelZ=PldrJS.Player.getVelZ=PldrJS.Player.velZ=PldrJS.Entity.velZ,PldrJS.Player.teleport=PldrJS.Entity.teleport,PldrJS.Player.pitch=PldrJS.Player.getPitch=PldrJS.Player.setPitch=PldrJS.Entity.pitch,PldrJS.Player.yaw=PldrJS.Player.getYaw=PldrJS.Player.setYaw=PldrJS.Entity.yaw,PldrJS.Player.level=PldrJS.Player.getLevel=PldrJS.Player.setLevel=PldrJS.Entity.level,PldrJS.Player.getPlayerEnt=function(a){return PldrJS.getServer().getPlayerExact(a)},PldrJS.Player.getPlayers=function(){var a=[];
//Java Collection -> JavaScript array
return PldrJS.getServer().getOnlinePlayers().values().forEach(function(b){a.push(b)}),a},PldrJS.Player.addItemInventory=function(a,b,c,d){a.getInventory().addItem(new $.Item(b,c,d))},PldrJS.Player.clientMessage=function(a,b){a.sendMessage(b)},PldrJS.Player.showTipMessage=function(a,b){a.sendTip(b)},PldrJS.Player.showPopupMessage=function(a,b,c){c=c||"",a.sendPopup(b,c)},
//======Script======
PldrJS.Script={},PldrJS.Script.Event=PldrEvent,PldrJS.Script.data={},PldrJS.Script.dataFile=new $.File("scripts/data.json"),PldrJS.Script.dataFile.exists())try{PldrJS.Script.data=JSON.parse($.Files.lines(PldrJS.Script.dataFile.toPath()).collect($.Collectors.joining("\n")))}catch(e){}else PldrJS.Script.dataFile.createNewFile();var isDataChanged=!1;PldrJS.Script.flush=function(){if(isDataChanged){var a=new $.BufferedWriter(new $.OutputStreamWriter(new $.FileOutputStream(PldrJS.Script.dataFile)));a.write(JSON.stringify(PldrJS.Script.data)),a.flush(),a.close(),isDataChanged=!1}},PldrJS.saveData=PldrJS.Script.saveData=function(a,b,c){isDataChanged=!0,void 0===PldrJS.Script.data[a]&&(PldrJS.Script.data[a]={}),PldrJS.Script.data[a][b]=c},PldrJS.loadData=PldrJS.Script.loadData=function(a,b){return PldrJS.Script.data[a][b]},PldrJS.removeData=PldrJS.Script.removeData=function(a,b){PldrJS.Script.data[a][b]=void 0,isDataChanged=!0};var isStopRequested=!1;PldrJS.disabled(function(){isStopRequested=!0,PldrJS.Script.flush()});var thread=new $.Thread(function(){for(;!isStopRequested;)PldrJS.Script.flush(),$.Thread.sleep(1e4)});thread.setName("PldrJS Save Thread"),thread.start(),module.exports=PldrJS;var _$=new JavaImporter(java.lang,Packages.cn.nukkit.command,Packages.cn.nukkit.utils),__$;try{__$=new JavaImporter(javafx.application,javafx.scene,javafx.scene.control,javafx.scene.layout);var thiz=void 0,mApplication=Java.extend(Java.type("javafx.application.Application"),{start:function(a){PldrJS.GUIEnabled=!0,PldrJS.Stage=a}});new _$.Thread(function(){try{__$.Application.launch(mApplication["class"])}catch(a){PldrJS.GUIEnabled=!1}}).start()}catch(e){PldrJS.GUIEnabled=!1}PldrJS.registerCommand("repl","Starts REPL Mode.","/repl"),PldrJS.command("repl",function(a,b,c,d){if(!(b instanceof _$.ConsoleCommandSender))return void b.sendMessage(_$.TextFormat.RED+"Please run this command in console");if(!PldrJS.GUIEnabled)return void b.sendMessage(_$.TextFormat.RED+"You cannot use gui!");var e,f;__$.Platform.runLater(function(){e=new __$.TextArea,e.setPrefColumnCount(50),e.setPrefRowCount(30),e.setPromptText("Enter statement here..."),f=new __$.TextArea,f.setPrefColumnCount(50),f.setPrefColumnCount(10),f.setEditable(!1),f.setStyle("-fx-opacity: 1.0;");var a=new __$.Button("Evaluate");a.setMaxWidth(_$.Double.MAX_VALUE),a.setOnAction(function(){new _$.Thread(function(){var a=Date.now(),b=new Function(e.getText()).apply(thiz,[]),c=Date.now()-a;__$.Platform.runLater(function(){f.setText(b+"\nElapsed Time : "+c+"ms")})}).start()});var b=new __$.ColumnConstraints;b.setFillWidth(!0),b.setHgrow(__$.Priority.ALWAYS);var c=new __$.RowConstraints;c.setFillHeight(!0),c.setVgrow(__$.Priority.ALWAYS);var d=new __$.GridPane;d.getColumnConstraints().add(b),d.getRowConstraints().add(c),d.add(new __$.Label("Statement"),0,0),d.add(e,0,1),d.add(a,0,2),d.add(f,0,3);var g=new __$.Scene(d);PldrJS.Stage.setScene(g),PldrJS.Stage.setTitle("REPL"),PldrJS.Stage.show()})});